const { Document, Packer, Paragraph, TextRun, HeadingLevel, Header, Footer, AlignmentType } = require('docx');

exports.handler = async (event, context) => {
  // Set CORS headers
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET, OPTIONS'
  };

  // Handle preflight requests
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers,
      body: ''
    };
  }

  try {
    const { docId, userData: userDataParam } = event.queryStringParameters;
    
    if (!docId) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'Missing docId parameter' })
      };
    }

    // Get user data from query parameters
    const userData = userDataParam ? JSON.parse(decodeURIComponent(userDataParam)) : {};
    
    // Create header content
    const headerContent = userData.userName ? 
      `Claim Navigator AI — Confidential Claim File
Policyholder: ${userData.userName} | Policy #: ${userData.policyNumber || 'N/A'} | Claim #: ${userData.claimNumber || 'N/A'}
Date of Loss: ${userData.dateOfLoss || 'N/A'} | Property: ${userData.propertyAddress || 'N/A'}` :
      'Claim Navigator AI — Confidential Claim File';

    // Create DOCX document with header and footer
    const doc = new Document({
      sections: [{
        properties: {
          page: {
            margin: {
              top: 1440, // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: headerContent,
                    size: 18,
                    color: "666666",
                  }),
                ],
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                children: [
                  new TextRun({
                    text: "© ClaimNavigatorAI — Confidential · Generated by Claim Navigator AI",
                    size: 16,
                    color: "999999",
                    italics: true,
                  }),
                ],
                alignment: AlignmentType.CENTER,
              }),
            ],
          }),
        },
        children: [
          new Paragraph({
            text: `${docId.replace(/-/g, ' ').toUpperCase()}`,
            heading: HeadingLevel.TITLE,
          }),
          new Paragraph({
            text: `Generated on: ${new Date().toLocaleDateString()}`,
          }),
          new Paragraph({
            text: '',
          }),
          new Paragraph({
            text: 'Document Information:',
            heading: HeadingLevel.HEADING_1,
          }),
          new Paragraph({
            text: `Document Type: ${docId}`,
          }),
          new Paragraph({
            text: `This is a DOCX export of the ${docId} document.`,
          }),
          new Paragraph({
            text: 'This document was generated using ClaimNavigatorAI Document Generator.',
          }),
        ],
      }],
    });

    // Generate DOCX buffer
    const buffer = await Packer.toBuffer(doc);
    const base64DOCX = buffer.toString('base64');

    return {
      statusCode: 200,
      headers: {
        ...headers,
        'Content-Type': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'Content-Disposition': `attachment; filename="${docId}.docx"`
      },
      body: base64DOCX,
      isBase64Encoded: true
    };

  } catch (error) {
    console.error('DOCX export error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ 
        error: 'Failed to generate DOCX',
        details: error.message 
      })
    };
  }
};
