const PDFDocument = require('pdfkit');

exports.handler = async (event, context) => {
  // Set CORS headers
  const headers = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Access-Control-Allow-Methods': 'GET, OPTIONS'
  };

  // Handle preflight requests
  if (event.httpMethod === 'OPTIONS') {
    return {
      statusCode: 200,
      headers,
      body: ''
    };
  }

  try {
    const { docId, userData: userDataParam } = event.queryStringParameters;
    
    if (!docId) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({ error: 'Missing docId parameter' })
      };
    }

    // Create PDF document
    const doc = new PDFDocument({
      size: 'A4',
      margins: {
        top: 50,
        bottom: 50,
        left: 50,
        right: 50
      }
    });

    // Buffer to store PDF data
    const buffers = [];
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {});

    // Add header
    doc.fontSize(9).fillColor('#666666')
       .text('Claim Navigator AI — Confidential Claim File', 50, 30);
    
    // Add user information header if available
    const userData = userDataParam ? JSON.parse(decodeURIComponent(userDataParam)) : {};
    if (userData.userName) {
      doc.fontSize(8).text(`Policyholder: ${userData.userName} | Policy #: ${userData.policyNumber || 'N/A'} | Claim #: ${userData.claimNumber || 'N/A'}`, 50, 45);
      doc.text(`Date of Loss: ${userData.dateOfLoss || 'N/A'} | Property: ${userData.propertyAddress || 'N/A'}`, 50, 55);
    }
    
    // Add main content
    doc.fontSize(20).fillColor('#000000').text(`${docId.replace(/-/g, ' ').toUpperCase()}`, 50, 80);
    doc.fontSize(12).text(`Generated on: ${new Date().toLocaleDateString()}`, 50, 110);
    
    // Add document-specific content
    doc.fontSize(14).text('Document Information:', 50, 150);
    doc.fontSize(12).text(`Document Type: ${docId}`, 50, 180);
    doc.text(`This is a PDF export of the ${docId} document.`, 50, 200);
    doc.text('This document was generated using ClaimNavigatorAI Document Generator.', 50, 220);
    
    // Add footer watermark
    const { width, height } = page.getSize();
    doc.fontSize(8).fillColor('#999999', 0.3)
       .text('© ClaimNavigatorAI — Confidential · Generated by Claim Navigator AI', 
             width/2 - 150, height - 30, { align: 'center' });

    // Finalize PDF
    doc.end();

    // Wait for PDF to be generated
    await new Promise((resolve) => {
      doc.on('end', resolve);
    });

    // Convert to base64
    const pdfBuffer = Buffer.concat(buffers);
    const base64PDF = pdfBuffer.toString('base64');

    return {
      statusCode: 200,
      headers: {
        ...headers,
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${docId}.pdf"`
      },
      body: base64PDF,
      isBase64Encoded: true
    };

  } catch (error) {
    console.error('PDF export error:', error);
    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({ 
        error: 'Failed to generate PDF',
        details: error.message 
      })
    };
  }
};
